//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roostersysteem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoosterDB : DbContext
    {
        public RoosterDB()
            : base("name=RoosterDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authenticator> Authenticators { get; set; }
        public virtual DbSet<LokaalType> LokaalTypes { get; set; }
        public virtual DbSet<Persoon> Persoons { get; set; }
        public virtual DbSet<PersoonUren> PersoonUrens { get; set; }
        public virtual DbSet<PersoonVak> PersoonVaks { get; set; }
        public virtual DbSet<Rooster> Roosters { get; set; }
        public virtual DbSet<UrenBeschikbaarheid> UrenBeschikbaarheids { get; set; }
        public virtual DbSet<UrenCollege> UrenColleges { get; set; }
        public virtual DbSet<Vak> Vaks { get; set; }
        public virtual DbSet<VakLokaalType> VakLokaalTypes { get; set; }
        public virtual DbSet<VakUrenCollege> VakUrenColleges { get; set; }
    }
}
